### PR TITLE
Handful of minor improvements

### PR DESCRIPTION
**Pull request by myw**
Found this great little library for my own purposes, and needed to make some tweaks, so I figured I'd see if you wanted them upstream:

- Merged in the r2 code: very useful
- Added UMD-style exports to make it work with pretty much any distribution system.
- Added options system, precision options
- Added some (basic) unit tests and linting
- Minor README improvements

### CODE REVIEW

**Comment by Tom-Alexander** [comment]
Thanks @myw, This looks really good. It's just missing a few dependencies (for the linter?). Are you able to add them?

**Comment by myw** [comment]
@Tom-Alexander sure thing. since i have them globally installed, I actually couldn't tell I was missing any (!) I think this is probably something I can get around with `nvm`, but just to be sure, was there anything besides `eslint-config-airbnb-es5` to add?

**Comment by Tom-Alexander** [comment]
Thanks @myw. Yeah `-g` can confuse things. There seems to be a few more missing dependencies associated with the linter:
```
babel-eslint
eslint
eslint-plugin-react
```

**Comment by Tom-Alexander** [comment]
👍

**Pull request merged**
